AllCops:
  TargetRubyVersion: 2.3.4
  TargetRailsVersion: 5.1.3
  Exclude:
    - db/schema.rb
    - config/**/*.rb
    - bin/*

Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/support/api/payload/*.rb'
    - 'spec/support/api/v1/payload/*.rb'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - lib/generators/object_generator.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/role.rb

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*.rb'
  Blacklist:
    - decrement!
    - decrement_counter
    - increment!
    - increment_counter
    - toggle!
    - update_attribute
    - update_column
    - update_columns
    - update_counters

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/PredicateName:
  NamePrefix:
    - has_
    - have_
  NamePrefixBlacklist:
    - is_
  Exclude:
    - 'app/serializers/**/*.rb'

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/ClassAndModuleChildren:
  Enabled: false
